# App configs
app:
  # App name
  name: ${KNOT_NAME:-knot}
  # Env mode (dev or prod)
  mode: ${KNOT_MODE:-prod}
  # HTTP port
  port: ${KNOT_PORT:-80}
  # Hostname
  hostname: ${KNOT_HOSTNAME:-127.0.0.1}
  # TLS configs
  tls:
    status: ${KNOT_TLS_STATUS:-off}
    crt_path: ${KNOT_TLS_PEMPATH:-cert/server.crt}
    key_path: ${KNOT_TLS_KEYPATH:-cert/server.key}

  # Global timeout
  timeout: ${KNOT_TIMEOUT:-50}

  # Application Database
  database:
      # database driver
      driver: ${KNOT_DB_DRIVER:-etcd}

      etcd:
        # etcd database name or prefix
        databaseName: ${KNOT_DB_ETCD_DB:-knot}
        # etcd username
        username: ${KNOT_DB_ETCD_USERNAME:- }
        # etcd password
        password: ${KNOT_DB_ETCD_PASSWORD:- }
        # etcd endpoints
        endpoints: ${KNOT_DB_ETCD_ENDPOINTS:-http://127.0.0.1:2379}
        # Timeout in seconds
        timeout: 30

  # Log configs
  log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${KNOT_LOG_LEVEL:-info}
    # Output can be stdout or abs path to log file /var/logs/knot.log
    output: ${KNOT_LOG_OUTPUT:-/var/logs/knot.log}
    # Format can be json
    format: ${KNOT_LOG_FORMAT:-json}
