# App configs
app:
  # App name
  name: ${CHAOS_NAME:-chaos}
  # Env mode (dev or prod)
  mode: ${CHAOS_MODE:-dev}
  # HTTP port
  port: ${CHAOS_PORT:-8000}
  # Hostname
  hostname: ${CHAOS_HOSTNAME:-127.0.0.1}
  # TLS configs
  tls:
    status: ${CHAOS_TLS_STATUS:-off}
    crt_path: ${CHAOS_TLS_PEMPATH:-cert/server.crt}
    key_path: ${CHAOS_TLS_KEYPATH:-cert/server.key}

  # API Credentials
  api:
    # API Key
    key: ${CHAOS_LOGIN_SECRET:-b08a1a8d-aefa-40fe-8473-59412ae46d11}

  # Global timeout
  timeout: ${CHAOS_TIMEOUT:-50}

  # Application Database
  database:
      # Database driver (sqlite3, mysql)
      driver: ${CHAOS_DATABASE_DRIVER:-sqlite3}
      # Database Host
      host: ${CHAOS_DATABASE_MYSQL_HOST:-localhost}
      # Database Port
      port: ${CHAOS_DATABASE_MYSQL_PORT:-3306}
      # Database Name
      name: ${CHAOS_DATABASE_MYSQL_DATABASE:-chaos.db}
      # Database Username
      username: ${CHAOS_DATABASE_MYSQL_USERNAME:-root}
      # Database Password
      password: ${CHAOS_DATABASE_MYSQL_PASSWORD:-root}

  # Log configs
  log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${CHAOS_LOG_LEVEL:-debug}
    # Output can be stdout or abs path to log file /var/logs/chaos.log
    output: ${CHAOS_LOG_OUTPUT:-stdout}
    # Format can be json
    format: ${CHAOS_LOG_FORMAT:-json}
