# App configs
app:
  # App name
  name: ${APP_NAME:-langmore}
  # Env mode (dev or prod)
  mode: ${APP_MODE:-dev}
  # HTTP port
  port: ${API_PORT:-8000}
  # Hostname
  hostname: ${API_HOSTNAME:-127.0.0.1}
  # TLS configs
  tls:
    status: ${API_TLS_STATUS:-off}
    crt_path: ${API_TLS_PEMPATH:-cert/server.crt}
    key_path: ${API_TLS_KEYPATH:-cert/server.key}

  # Global timeout
  timeout: ${API_TIMEOUT:-50}

  # Kubernetes Clusters
  clusters:
      -
          name: ${KUBE_CLUSTER_01_NAME:-production}
          inCluster: ${KUBE_CLUSTER_01_IN_CLUSTER:-false}
          kubeconfig: ${KUBE_CLUSTER_01_CONFIG_FILE:-/app/configs/production-cluster-kubeconfig.yaml}
      -
          name: ${KUBE_CLUSTER_02_NAME:-staging}
          inCluster: ${KUBE_CLUSTER_02_IN_CLUSTER:-false}
          kubeconfig: ${KUBE_CLUSTER_02_CONFIG_FILE:-/app/configs/staging-cluster-kubeconfig.yaml}

  # Log configs
  log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${LOG_LEVEL:-info}
    # Output can be stdout or abs path to log file /var/logs/langmore.log
    output: ${LOG_OUTPUT:-stdout}
    # Format can be json
    format: ${LOG_FORMAT:-json}
