version: '3'

services:

  prometheus:
    image: 'prom/prometheus:v2.53.1'
    volumes:
      - '/root/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - '9090'
    restart: unless-stopped

  grafana:
    image: 'grafana/grafana:11.1.3'
    environment:
      - 'GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}'
      - '_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}'
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - '3000'
    restart: unless-stopped
